### ISSUE TITLE
Setting up the Environment

### ISSUE THREAD

**Issue by ro9ues** [ro9ues/ro9ues.github.io#1]
### Description

Set up the project that will contain the implementation of The House of Rogues.

---

### Issue Checklist

- [x] Install `ruby`, `jekyll`.
- [x] Create project with `jekyll new` command.
- [x] Configure a project with which we can easily lint and test all our code.

---

### Assignees

- [x] Final assign @ro9ues

**Comment by imrogues** [comment]
I’m working on my way! 😉

**Comment by ro9ues** [comment]
#### Review Status

_Code Review_ was done successfully.

**Comment by ro9ues** [comment]
I’m closing this issue.
Please see **[v0.1.0-alpha.1 – Setting up The House of Rogues [PR]](https://github.com/ro9ues/ro9ues.github.io/pull/8)**.
