### ISSUE TITLE
About

### ISSUE THREAD

**Issue by ro9ues** [ro9ues/ro9ues.github.io#3]
### Description

Create the about page for The House of Rogues.

---

### Issue Checklist

- [x] Write the needed tests.
- [x] Create the markup for the component.
- [x] Add the correct styles.
- [x] Use the *lint* to clean `CSS` code.
- [x] Document all things.

---

### Assignees

- [x] Final assign @ro9ues

**Comment by imrogues** [comment]
I’m working on my way! 😉

**Comment by ro9ues** [comment]
#### Review Status

_Code Review_ was done successfully.

**Comment by ro9ues** [comment]
I’m closing this issue.
Please see **[v0.1.0-alpha.1 – Setting up The House of Rogues [PR]](https://github.com/ro9ues/ro9ues.github.io/pull/8)**.
