### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by ro9ues** [ro9ues/ro9ues.github.io#5]
### Description

Add the correct SEO tags from Open Graph, Twitter, Schema, Google, and browser native tags.

---

### Issue Checklist

- [x] Add each correct and current tag available for website.
- [x] Fill with the correct information.

---

### Assignees

- [x] Final assign @ro9ues

**Comment by imrogues** [comment]
I’m working on my way! 😉

**Comment by ro9ues** [comment]
#### Review Status

_Code Review_ was done successfully.

**Comment by ro9ues** [comment]
I’m closing this issue.
Please see **[v0.1.0-alpha.1 – Setting up The House of Rogues [PR]](https://github.com/ro9ues/ro9ues.github.io/pull/8)**.
