### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by ro9ues** [ro9ues/ro9ues.github.io#7]
### Description

Enable Continuous Integration.

---

### Issue Checklist

- [x] Enable project to implement Continuous Integration.
- [x] Configure `Travis CI`.

---

### Assignees

- [x] Final assign @ro9ues

**Comment by imrogues** [comment]
I’m working on my way! 😉

**Comment by ro9ues** [comment]
#### Review Status

_Code Review_ was done successfully.

**Comment by ro9ues** [comment]
I’m closing this issue.
Please see **[v0.1.0-alpha.1 – Setting up The House of Rogues [PR]](https://github.com/ro9ues/ro9ues.github.io/pull/8)**.
